# wrangler.toml - Cloudflare Pages Configuration

name = "patigonulluleri"
compatibility_date = "2024-01-01"

# Pages configuration
pages_build_output_dir = "client"

# D1 Database binding (for subscriptions)
[[d1_databases]]
binding = "DB"
database_name = "pago-subscriptions"
database_id = "e8e77fa4-7875-4ca9-bb70-685d6371f2d0"

# KV namespace (for rate limiting)
[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "5b85cacbce7d442b8e6aa496986cced7"

# Environment variables (non-sensitive)
[vars]
FRONTEND_URL = "https://patigonulluleri.com"
FIREBASE_PROJECT_ID = "patigonulluleri-1193e"

# Secrets (set via: wrangler secret put SECRET_NAME)
# - RESEND_API_KEY
# - FIREBASE_API_KEY
# - ADMIN_SECRET

# ============================================
# CRON WORKER (Separate Worker for notifications)
# ============================================

[[workers]]
name = "pago-notification-scheduler"
main = "workers/notification-scheduler.js"
compatibility_date = "2024-01-01"

# This worker needs access to both D1 and Firebase
[[workers.d1_databases]]
binding = "DB"
database_name = "pago-subscriptions"
database_id = "e8e77fa4-7875-4ca9-bb70-685d6371f2d0"

[workers.vars]
FIREBASE_PROJECT_ID = "patigonulluleri-1193e"
FRONTEND_URL = "https://patigonulluleri.com"