name = "pago-notification-scheduler"
main = "notification-scheduler.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["0 * * * *"]

[vars]
FIREBASE_PROJECT_ID = "patigonulluleri-1193e"
FRONTEND_URL = "https://patigonulluleri.com"

