name = "pago-notification-scheduler"
main = "notification-scheduler.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["0 * * * *"]

[vars]
FIREBASE_PROJECT_ID = "patigonulluleri-1193e"
FRONTEND_URL = "https://patigonulluleri.com"

[[d1_databases]]
binding = "DB"
database_name = "pago-subscriptions"
database_id = "e8e77fa4-7875-4ca9-bb70-685d6371f2d0"